name: learn-github-actions
on:
  push:
    branches:
      - release

env:
  MY_SERVER_PRIVATE_KEY:  ${{secrets.MY_SERVER_PRIVATE_KEY}}
  MY_SERVER_USER: root
  MY_SERVER_IP: 101.35.35.56
  My_SERVER_PRIVATE_KEY_PLUS : -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAnMxytNX/qJZfmAkrIjCT4fM6Uu/vzy4RB66Czu4SZvBbpn45ABBa
nVT7LHCeuMCoY2Q4DKhG5/jHlYsssVxV3FjisDsMb9h2064uq2TtTfZSvEMzaptlioyTsS
aCrnaajo5pzu+37FPOiejd8gY9U/1FJKzYS4yF89EttLyQCqGbFHzPqbgJaTs7yss8Lj6H
snHy64SfM+AQbNs924gcgqbYs3PnW7BW3IktS1+nOWIYB5POHc1WQNP/fpCDXjNeoGE2B0
D6P/e0SQCqMXL55gnN4dZakDtiIqAhVT0Mo+yOruHiDxIOM+4mt4TZ8hAkeFmf4V7EfEPM
pD+82KRaG0k75xX2o7X+9EekxSiriypXNyogZ2Of6pCpg1YR5vxke3jX/rp7xG6zhK/iNb
aeu4M/+el/UT/09uvwzmPjNOzawoQH7qHWON+yGJSVSxXkCJV91mdBhGzglmuaQKf61Nn+
UNrcKYox3MAsKaobHrX8qDoaWUV5l6xo2zgJMOWvAAAFiJ/bh5if24eYAAAAB3NzaC1yc2
EAAAGBAJzMcrTV/6iWX5gJKyIwk+HzOlLv788uEQeugs7uEmbwW6Z+OQAQWp1U+yxwnrjA
qGNkOAyoRuf4x5WLLLFcVdxY4rA7DG/YdtOuLqtk7U32UrxDM2qbZYqMk7Emgq52mo6Oac
7vt+xTzono3fIGPVP9RSSs2EuMhfPRLbS8kAqhmxR8z6m4CWk7O8rLPC4+h7Jx8uuEnzPg
EGzbPduIHIKm2LNz51uwVtyJLUtfpzliGAeTzh3NVkDT/36Qg14zXqBhNgdA+j/3tEkAqj
Fy+eYJzeHWWpA7YiKgIVU9DKPsjq7h4g8SDjPuJreE2fIQJHhZn+FexHxDzKQ/vNikWhtJ
O+cV9qO1/vRHpMUoq4sqVzcqIGdjn+qQqYNWEeb8ZHt41/66e8Rus4Sv4jW2nruDP/npf1
E/9Pbr8M5j4zTs2sKEB+6h1jjfshiUlUsV5AiVfdZnQYRs4JZrmkCn+tTZ/lDa3CmKMdzA
LCmqGx61/Kg6GllFeZesaNs4CTDlrwAAAAMBAAEAAAGBAIXlIF7ED1lLb75ItgiwKthb94
YzVjk5QVmp8BH8wsIcpmb6ino/fOG1W/eLBD8IZcLaJfLJECOvEd/lxPh/vOI5FPsgsXIh
CvegWkIKIYrdubECQbnbkU5K1SQFmrqYlUr+2ePYWNr6hfjGXiD6qww5zv2Oi/WXvhuCmO
Ep1Gb/sYpBOqPXgFHYPyrhejaTNxVusN3lln2Z7OzIG36IMLBxAcPcScjGQKZ6ja87s3UR
CywNT4mreuhJIHhXt5aNjf5XOmYr72XjMXv1VcBuyAeD8mL+jHMCIuHjOgBfvH6eaMlkUh
0hD20zXSSVj7aNv1FCuynLSffja2BAFhNmeLfkh41rrjeFIFcxzSUKS1xITVs+TGn0yzKE
s7b/aIXhRcUnfpdCbmfHx+/bFij2cotV17tfodFfxA22zmB0NFg97GDyVkTbw1nnE6epnl
IuwmW30RnEteUWeTf4cA02KEj8ENvzmXiq4Px2e5zNG+I2R98xqtIiw9NFtZ4erI0p4QAA
AMBP7gVHQ6Zd9Tgy+NeC87+aFfjZdGJficeMfDx7W1/o1RyrLlF8Wnof1kzdszK3aBgH16
fAo+gQFke5zxTfFJNh4C7e0/Gh0hOfbkp03VtRZHuibRTiq+xAM4tFJE2M5g108waMk42h
JbkFuZcQfUchTcvgsm22QCNaSLJCKD/evCzjGwS6nrhssKxex1OU6qu6YQBggzr4HS9H3i
Hq0wntGoj/0HD1UpP2WUqiDsVxWEskIYv5zCzzQOY/3XaGDc4AAADBAM6p979fS5VcIdJn
OtD7kmJeiHcCz0KLeubuZ1MNoGkjcCA6lYHsMJLixTraVA3gKsoe9xOAmmeBzKdEFeRCsZ
8UW2Y+LfOZHZjtPE1tlUocsLvyK7sE3/oObFn8IQSnmJ+x8zojYkXsKxo17Fqr/kX9NtcO
UaSb2l2rHT/QswtLBnUuZy8onS2rT14GHN/i1iIaXZhS2aE/A6v2hi5RwmBvsnM333jNK9
SXI6jsm8U2HcstzaFFpqF4RLocGzTtZQAAAMEAwjsEsTWfujQe/eV0CNsM4F05Rcm4kHYJ
uUv5jrhgGx4h1VmS1/hWzYyo+beMqTCNYeH4NntJMMh/uXMRtFZ6VABUQzPEWueLNfrbav
GFJLGbRF1EEJ3Q3igmdKryMhTr4uOMc6M0dFzzfpJOGqi4ILs2YVhPNYRn+M7QfIDnwelj
TVJyn6nIixMYba7ZDHM9O9QcqtA2cH0nVrv2dXGyTTO+PkN3vVyuBiZl5YBKDVqSHfqPaf
i75cioXbDSgI+DAAAAEnJvb3RAVk0tNC0yLXVidW50dQ==
-----END OPENSSH PRIVATE KEY-----
  cache-name: 2020
jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - name : Printf the ENV
        run  : echo "The IP is ${{ env.MY_SERVER_IP }} , The User is ${{ env.MY_SERVER_USER }} , The Private_Key is ${{env.MY_SERVER_PRIVATE_KEY}} The Key is ${{ env.MY_SERVER_PRIVATE_KEY_PLUS }}"
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 14
      # - name : Install Dependency
      #   run: npm install
      # - name : Build the Blog
      #   run: npm run build
      # - name: Restart server # 第三步，重启服务
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ env.MY_SERVER_IP }} # 下面三个配置与上一步类似
      #     username: ${{ env.MY_SERVER_USER }}
      #     key: ${{ env.MY_SERVER_PRIVATE_KEY }}
      #     # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
      #     script: |
      #       cd ..
      #       ls
      #       docker ps
      #       docker image ls
      # - name: Deploy to Server # 第二步，rsync推文件
      #   uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
      #   env:
      #     DEPLOY_KEY: ${{ env.MY_SERVER_PRIVATE_KEY }} # 引用配置，SSH私钥
      #     ARGS: -avz --delete --exclude='' # rsync参数，排除.pyc文件
      #     SERVER_PORT: '22' # SSH端口
      #     FOLDER: build # 要推送的文件夹，路径相对于代码仓库的根目录
      #     SERVER_IP: ${{ env.MY_SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
      #     USERNAME: ${{ env.MY_SERVER_USER }} # 引用配置，服务器登录名
      #     SERVER_DESTINATION: ./home/ubuntu/Blog/Deploy # 部署到目标文件夹

