name: learn-github-actions
on:
  push:
    branches:
      - release

env:
  MY_SERVER_PRIVATE_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAnMxytNX/qJZfmAkrIjCT4fM6Uu/vzy4RB66Czu4SZvBbpn45ABBanVT7LHCeuMCoY2Q4DKhG5/jHlYsssVxV3FjisDsMb9h2064uq2TtTfZSvEMzaptlioyTsSaCrnaajo5pzu+37FPOiejd8gY9U/1FJKzYS4yF89EttLyQCqGbFHzPqbgJaTs7yss8Lj6HsnHy64SfM+AQbNs924gcgqbYs3PnW7BW3IktS1+nOWIYB5POHc1WQNP/fpCDXjNeoGE2B0D6P/e0SQCqMXL55gnN4dZakDtiIqAhVT0Mo+yOruHiDxIOM+4mt4TZ8hAkeFmf4V7EfEPMpD+82KRaG0k75xX2o7X+9EekxSiriypXNyogZ2Of6pCpg1YR5vxke3jX/rp7xG6zhK/iNbaeu4M/+el/UT/09uvwzmPjNOzawoQH7qHWON+yGJSVSxXkCJV91mdBhGzglmuaQKf61Nn+UNrcKYox3MAsKaobHrX8qDoaWUV5l6xo2zgJMOWvAAAFiJ/bh5if24eYAAAAB3NzaC1yc2EAAAGBAJzMcrTV/6iWX5gJKyIwk+HzOlLv788uEQeugs7uEmbwW6Z+OQAQWp1U+yxwnrjAqGNkOAyoRuf4x5WLLLFcVdxY4rA7DG/YdtOuLqtk7U32UrxDM2qbZYqMk7Emgq52mo6Oac7vt+xTzono3fIGPVP9RSSs2EuMhfPRLbS8kAqhmxR8z6m4CWk7O8rLPC4+h7Jx8uuEnzPgEGzbPduIHIKm2LNz51uwVtyJLUtfpzliGAeTzh3NVkDT/36Qg14zXqBhNgdA+j/3tEkAqjFy+eYJzeHWWpA7YiKgIVU9DKPsjq7h4g8SDjPuJreE2fIQJHhZn+FexHxDzKQ/vNikWhtJO+cV9qO1/vRHpMUoq4sqVzcqIGdjn+qQqYNWEeb8ZHt41/66e8Rus4Sv4jW2nruDP/npf1E/9Pbr8M5j4zTs2sKEB+6h1jjfshiUlUsV5AiVfdZnQYRs4JZrmkCn+tTZ/lDa3CmKMdzALCmqGx61/Kg6GllFeZesaNs4CTDlrwAAAAMBAAEAAAGBAIXlIF7ED1lLb75ItgiwKthb94YzVjk5QVmp8BH8wsIcpmb6ino/fOG1W/eLBD8IZcLaJfLJECOvEd/lxPh/vOI5FPsgsXIhCvegWkIKIYrdubECQbnbkU5K1SQFmrqYlUr+2ePYWNr6hfjGXiD6qww5zv2Oi/WXvhuCmOEp1Gb/sYpBOqPXgFHYPyrhejaTNxVusN3lln2Z7OzIG36IMLBxAcPcScjGQKZ6ja87s3URCywNT4mreuhJIHhXt5aNjf5XOmYr72XjMXv1VcBuyAeD8mL+jHMCIuHjOgBfvH6eaMlkUh0hD20zXSSVj7aNv1FCuynLSffja2BAFhNmeLfkh41rrjeFIFcxzSUKS1xITVs+TGn0yzKEs7b/aIXhRcUnfpdCbmfHx+/bFij2cotV17tfodFfxA22zmB0NFg97GDyVkTbw1nnE6epnlIuwmW30RnEteUWeTf4cA02KEj8ENvzmXiq4Px2e5zNG+I2R98xqtIiw9NFtZ4erI0p4QAAAMBP7gVHQ6Zd9Tgy+NeC87+aFfjZdGJficeMfDx7W1/o1RyrLlF8Wnof1kzdszK3aBgH16fAo+gQFke5zxTfFJNh4C7e0/Gh0hOfbkp03VtRZHuibRTiq+xAM4tFJE2M5g108waMk42hJbkFuZcQfUchTcvgsm22QCNaSLJCKD/evCzjGwS6nrhssKxex1OU6qu6YQBggzr4HS9H3iHq0wntGoj/0HD1UpP2WUqiDsVxWEskIYv5zCzzQOY/3XaGDc4AAADBAM6p979fS5VcIdJnOtD7kmJeiHcCz0KLeubuZ1MNoGkjcCA6lYHsMJLixTraVA3gKsoe9xOAmmeBzKdEFeRCsZ8UW2Y+LfOZHZjtPE1tlUocsLvyK7sE3/oObFn8IQSnmJ+x8zojYkXsKxo17Fqr/kX9NtcOUaSb2l2rHT/QswtLBnUuZy8onS2rT14GHN/i1iIaXZhS2aE/A6v2hi5RwmBvsnM333jNK9SXI6jsm8U2HcstzaFFpqF4RLocGzTtZQAAAMEAwjsEsTWfujQe/eV0CNsM4F05Rcm4kHYJuUv5jrhgGx4h1VmS1/hWzYyo+beMqTCNYeH4NntJMMh/uXMRtFZ6VABUQzPEWueLNfrbavGFJLGbRF1EEJ3Q3igmdKryMhTr4uOMc6M0dFzzfpJOGqi4ILs2YVhPNYRn+M7QfIDnweljTVJyn6nIixMYba7ZDHM9O9QcqtA2cH0nVrv2dXGyTTO+PkN3vVyuBiZl5YBKDVqSHfqPafi75cioXbDSgI+DAAAAEnJvb3RAVk0tNC0yLXVidW50dQ==\n-----END OPENSSH PRIVATE KEY-----"
  MY_SERVER_USER: root
  MY_SERVER_IP: 101.35.35.56
  My_SERVER_PRIVATE_KEY_PLUS : ${{secrets.MY_SERVER_PRIVATE_KEY}}
  cache-name: 2020
jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name : Install Dependency
        run: npm install
      - name : Build the Blog
        run: npm run build
      - name : Printf the ENV
        run  : echo "The IP is ${{ env.MY_SERVER_IP }} , The User is ${{ env.MY_SERVER_USER }} , The Private_Key is ${{env.MY_SERVER_PRIVATE_KEY}} "
      - name : Print
        run  : echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ env.MY_SERVER_PRIVATE_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='' # rsync参数，排除.pyc文件
          SERVER_PORT: '22' # SSH端口
          FOLDER: build # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ env.MY_SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ env.MY_SERVER_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ./home/ubuntu/Blog/Deploy # 部署到目标文件夹
      - name: Restart server # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.MY_SERVER_IP }} # 下面三个配置与上一步类似
          username: ${{ env.MY_SERVER_USER }}
          key: ${{ env.MY_SERVER_PRIVATE_KEY }}
          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
          script: |
            ls
