name: learn-github-actions
on:
  push:
    branches:
      - release

env:
  MY_SERVER_PRIVATE_KEY: ${{ secrets.MY_SERVER_PRIVATE_KEY }} # 服务器私钥
  MY_SERVER_USER: ${{ secrets.MY_SERVER_USER }}
  MY_SERVER_IP: ${{ secrets.MY_SERVER_IP }}
  cache-name: 2020
jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name : Install Dependency
        run: npm install
      - name : Build the Blog
        run: npm run build
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  Deploy:
    name: Deploy
    needs: build-production
    runs-on: ubuntu-latest
    steps:
    - name: Download result
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ env.MY_SERVER_PRIVATE_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='' # rsync参数，排除.pyc文件
          SERVER_PORT: '22' # SSH端口
          FOLDER: build # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ env.MY_SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ env.MY_SERVER_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ./home/ubuntu/Blog/Deploy # 部署到目标文件夹
