name: learn-github-actions
on:
  push:
    branches:
      - release

env:
  MY_SERVER_PRIVATE_KEY:  ${{secrets.MY_SERVER_PRIVATE_KEY}}
  MY_SERVER_USER: "root"
  MY_SERVER_IP: "101.35.35.56"
  My_SERVER_PRIVATE_KEY_PLUS : xasasa
  cache-name: 2020
jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - name : Printf the ENV
        run  : echo "The IP is ${{ env.MY_SERVER_IP }} , The User is ${{ env.MY_SERVER_USER }} , The Private_Key is ${{env.MY_SERVER_PRIVATE_KEY}} The Key is ${{ env.My_SERVER_PRIVATE_KEY_PLUS }}"
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 14
      # - name : Install Dependency
      #   run: npm install
      # - name : Build the Blog
      #   run: npm run build
      - name: Restart server # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.MY_SERVER_IP }} # 下面三个配置与上一步类似
          username: ${{ env.MY_SERVER_USER }}
          password : "zlh011228"
          # key: ${{ env.MY_SERVER_PRIVATE_KEY }}
          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
          script: |
            cd ..
            ls
            docker ps
            docker image ls
      # - name: Deploy to Server # 第二步，rsync推文件
      #   uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
      #   env:
      #     DEPLOY_KEY: ${{ env.MY_SERVER_PRIVATE_KEY }} # 引用配置，SSH私钥
      #     ARGS: -avz --delete --exclude='' # rsync参数，排除.pyc文件
      #     SERVER_PORT: '22' # SSH端口
      #     FOLDER: build # 要推送的文件夹，路径相对于代码仓库的根目录
      #     SERVER_IP: ${{ env.MY_SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
      #     USERNAME: ${{ env.MY_SERVER_USER }} # 引用配置，服务器登录名
      #     SERVER_DESTINATION: ./home/ubuntu/Blog/Deploy # 部署到目标文件夹

